export const IPC = {
  navigate: 'obsrv:navigate',
  reload: 'obsrv:reload',
  back: 'obsrv:back',
  forward: 'obsrv:forward',
  setViewport: 'obsrv:set-viewport',
  setNativeBounds: 'obsrv:set-native-bounds',
  setMode: 'obsrv:set-mode',
  sendInput: 'obsrv:send-input',
  getHostInfo: 'obsrv:get-host-info',
  getSettings: 'obsrv:get-settings',
  setSettings: 'obsrv:set-settings',
  frame: 'obsrv:frame',
  frameSubscribe: 'obsrv:frame-subscribe',
  urlChanged: 'obsrv:url-changed',
  loadError: 'obsrv:load-error',
  hostChanged: 'obsrv:host-changed',
  targetLoading: 'obsrv:target-loading',
  targetNavigating: 'obsrv:target-navigating',
  syncScroll: 'obsrv:sync-scroll',
  applyScroll: 'obsrv:apply-scroll',
  openImage: 'obsrv:open-image',
  focusUrl: 'obsrv:focus-url',
  openImagePath: 'obsrv:open-image-path',
  readImageFile: 'obsrv:read-image-file',
} as const
